### ISSUE TITLE
sdrangelsrv remote TCP sink not working

### ISSUE THREAD

**Issue by SteveHawk** [f4exb/sdrangel#2470]
Hey guys, I tried to setup a headless raspberry pi with `sdrangelsrv` running in docker with an RTL-SDR dongle, but could not get remote TCP sink to work.

The remote sink plugin using UDP does work, but when I switched to the TCP sink, server log shows a ton of overflow and dropped messages, and no waterfall shows up on the sdrangel client. Could you help me out here?

The client interface after connecting to the server:

![Image](https://github.com/user-attachments/assets/36367e70-d62b-4c90-87d6-5a013755ce27)

The prefill buffer fills to 1s then back to 0 then to 1 and so on, but never starts showing the waterfall and spectrum.

The error logs on server:

```log
sdrangel     | 2025-06-18 10:47:00.680 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) 3 messages dropped
sdrangel     | 2025-06-18 10:47:00.681 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) overflow - dropping 3072 samples
sdrangel     | 2025-06-18 10:47:00.922 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) overflow - dropping 4096 samples
sdrangel     | 2025-06-18 10:47:03.437 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) 217 messages dropped
sdrangel     | 2025-06-18 10:47:03.437 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) overflow - dropping 4096 samples
sdrangel     | 2025-06-18 10:47:03.442 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) overflow - dropping 4096 samples
sdrangel     | 2025-06-18 10:47:06.296 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) 229 messages dropped
sdrangel     | 2025-06-18 10:47:06.296 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) overflow - dropping 4096 samples
sdrangel     | 2025-06-18 10:47:06.300 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) overflow - dropping 4096 samples
sdrangel     | 2025-06-18 10:47:08.803 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) 229 messages dropped
sdrangel     | 2025-06-18 10:47:08.803 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) overflow - dropping 4096 samples
sdrangel     | 2025-06-18 10:47:08.807 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) overflow - dropping 4096 samples
sdrangel     | 2025-06-18 10:47:09.500 (D) RemoteTCPSinkSink::errorOccurred:  QAbstractSocket::RemoteHostClosedError
sdrangel     | 2025-06-18 10:47:09.500 (D) RemoteTCPSinkSink::disconnected
sdrangel     | 2025-06-18 10:47:20.919 (D) RemoteTCPSinkSink::acceptTCPConnection: client connected
sdrangel     | 2025-06-18 10:47:22.209 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) 77 messages dropped
sdrangel     | 2025-06-18 10:47:22.209 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) overflow - dropping 3072 samples
sdrangel     | 2025-06-18 10:47:22.213 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) overflow - dropping 4096 samples
sdrangel     | 2025-06-18 10:47:25.022 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) 219 messages dropped
sdrangel     | 2025-06-18 10:47:25.023 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) overflow - dropping 3072 samples
sdrangel     | 2025-06-18 10:47:25.027 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) overflow - dropping 4096 samples
sdrangel     | 2025-06-18 10:47:27.828 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) 216 messages dropped
sdrangel     | 2025-06-18 10:47:27.828 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) overflow - dropping 3072 samples
sdrangel     | 2025-06-18 10:47:27.833 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) overflow - dropping 4096 samples
sdrangel     | 2025-06-18 10:47:30.638 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) 218 messages dropped
sdrangel     | 2025-06-18 10:47:30.638 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) overflow - dropping 3072 samples
sdrangel     | 2025-06-18 10:47:30.642 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) overflow - dropping 4096 samples
sdrangel     | 2025-06-18 10:47:33.448 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) 218 messages dropped
sdrangel     | 2025-06-18 10:47:33.448 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) overflow - dropping 3072 samples
sdrangel     | 2025-06-18 10:47:33.453 (C) SampleSinkFifo::write: (RemoteTCPSink [0:0]) overflow - dropping 4096 samples
sdrangel     | 2025-06-18 10:47:35.288 (D) RemoteTCPSinkSink::errorOccurred:  QAbstractSocket::RemoteHostClosedError
sdrangel     | 2025-06-18 10:47:35.288 (D) RemoteTCPSinkSink::disconnected
```

This is the startup command I used:
`/opt/install/sdrangel/bin/sdrangelsrv -w /home/sdr/.config/sdrangel/fftw-wisdom --remote-tcp --remote-tcp-hwtype RTLSDR`

And this is the complete compose.yaml:

```yaml
---
services:
  sdrangel:
    image: "f4exb06/sdrangelsrv:v7.22.7"
    container_name: "sdrangel"
    init: true
    restart: unless-stopped
    ports:
      - "8091:8091"  # API
      - "1234:1234"  # remote tcp
      # - "8887:8887"  # spectrum
      # - "9090:9090/udp"  # remote input udp port
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    environment:
      FFTWFILE: "fftw-wisdom"
      LD_LIBRARY_PATH: "/opt/install/libsdrplay/lib:/opt/install/xtrx-images/lib"
    volumes:
      - "/home/steve/Applications/services/sdrangel/configs:/home/sdr/.config:rw"
    entrypoint:
      - /opt/install/sdrangel/bin/sdrangelsrv
      - -w
      - /home/sdr/.config/sdrangel/fftw-wisdom
      - --remote-tcp
      - --remote-tcp-hwtype
      - RTLSDR

  sdrangelcli:
    image: "f4exb06/sdrangelcli:v4.0.2"
    container_name: "sdrangelcli"
    init: true
    restart: unless-stopped
    ports:
      - "8080:8080"
```

I did also try running `rtl_tcp` and `spyserver` on the raspi, both work with sdrangel client using default settings. So it appears the client should be working fine, but the server side `sdrangelsrv` for some reason is failing to send out samples?
